import { from } from 'rxjs';

export { VerDetallesPage } from './Noticias/ver-detalles/ver-detalles'
export { TabsPage } from './tabs/tabs';
export { AreasDeportivasYCafeteriasPage } from './CroquisUni/areas-deportivas-y-cafeterias/areas-deportivas-y-cafeterias';
export { VerDetallesCroquisPage } from './CroquisUni/ver-detalles-croquis/ver-detalles-croquis';
export { ConoceUnipoliPage } from './CroquisUni/conoce-unipoli/conoce-unipoli';
export { Ud1Page } from './CroquisUni/ud1/ud1';
export { Ud2Page } from './CroquisUni/ud2/ud2';
export { Ud3Page } from './CroquisUni/ud3/ud3';
export { CentroInformacionPage } from './CroquisUni/centro-informacion/centro-informacion';
export { LaboratoriosPage } from './CroquisUni/laboratorios/laboratorios';
export { EnlacesPage } from './enlaces/enlaces';
export { HomePage } from "./Noticias/home/home";
export { InformacionEventosPage } from "./Eventos/informacionEventos/informacionEventos";
export { InformacionPage } from "./Eventos/informacion/informacion";
export { AlumnoPage } from "./login/alumno/alumno";
export { LoginPage } from "./login/login/login";
export { OlvidarcontraceñaPage } from "./login/olvidarcontraceña/olvidarcontraceña";
export { RegistroPage } from "./login/registro/reistro";
export { SeleccionarCarreraPage } from "./login/seleccionar-carrera/seleccionar-carrera";
export { HorariosPage } from './HorariosCarre/horarios/horarios';
export { GruposPage } from './HorariosCarre/grupos/grupos';
export { GrupoiswPage } from './HorariosCarre/grupoisw/grupoisw';
export { HorariosIswPage } from './HorariosCarre/horarios-isw/horarios-isw';
export { HorariosAmbPage } from './HorariosCarre/horarios-amb/horarios-amb';
export { GrupoambPage } from './HorariosCarre/grupoamb/grupoamb';
export { HorariosCivPage } from './HorariosCarre/horarios-civ/horarios-civ';
export { GrupocivPage } from './HorariosCarre/grupociv/grupociv';
export { HorariosIrtPage } from './HorariosCarre/horarios-irt/horarios-irt';
export { GrupoirtPage } from './HorariosCarre/grupoirt/grupoirt';
export { HorariosItmPage } from './HorariosCarre/horarios-itm/horarios-itm';
export { GrupoitmPage } from './HorariosCarre/grupoitm/grupoitm';
export { HorariosPyMesPage } from './HorariosCarre/horarios-py-mes/horarios-py-mes';
export { GrupopymesPage } from './HorariosCarre/grupopymes/grupopymes';
export { AgregarPage } from './agregar/agregar';
/*export { MsjAmbPage } from './Noticias/msj-amb/msj-amb';
export { MsjCivPage } from './Noticias/msj-civ/msj-civ';
export { MsjManuPage } from './Noticias/msj-manu/msj-manu';
export { MsjPyMPage } from './Noticias/msj-py-m/msj-py-m';
export { MsjTelePage } from './Noticias/msj-tele/msj-tele';
export { MensajesTabsPage } from './Noticias/mensajes-tabs/mensajes-tabs';
*/
export { CroquisUniPage } from './aspirantes/croquis-uni/croquis-uni';
export { DirectorioInstiPage } from './aspirantes/directorio-insti/directorio-insti';
export { OfertaAcademicaPage } from './aspirantes/oferta-academica/oferta-academica';
export { PaaldohadeservirPage } from './aspirantes/paaldohadeservir/paaldohadeservir';
export { UniversidadPage } from './aspirantes/universidad/universidad';
export { TabsAspiPage } from './aspirantes/tabs-aspi/tabs-aspi';
export { CarreraRegistroPage } from './login/carrera-registro/carrera-registro';
export { InforegistroPage } from './login/inforegistro/inforegistro';
export { DatosdusuarioPage } from './login/datosdusuario/datosdusuario'
export { LoginStatePage } from './login/login-state/login-state'